/* {
    "Analytics": {
      "id": "UUID",
      "reportType": "Patient Trends | Revenue | Treatment Effectiveness | Doctor Performance",
      "dateRange": {
        "startDate": "date",
        "endDate": "date"
      },
      "generatedBy": "UUID (Ref to User)",
      "data": {
        "metrics": [
          {
            "metricName": "string",
            "value": "decimal",
            "changePercentage": "decimal",
            "trend": "Up | Down | Neutral"
          }
        ]
      },
      "exportUrl": "string (PDF/CSV link)",
      "createdAt": "timestamp"
    }
  } */
    var sequelize = require("../db/init.sequelize.js");
    var Sequelize = require("sequelize");
    
    var Analytics = sequelize.define("analytics", {
      id: {
        type: Sequelize.UUID,
        defaultValue: Sequelize.UUIDV4,
        primaryKey: true,
      },
      reportType: {
        type: Sequelize.ENUM(
          "Patient Trends",
          "Revenue",
          "Treatment Effectiveness",
          "Doctor Performance"
        ),
        allowNull: false,
      },
      startDate: {
        type: Sequelize.DATE,
        allowNull: false,
      },
      endDate: {
        type: Sequelize.DATE,
        allowNull: false,
      },
      generatedBy: {
        type: Sequelize.UUID,
        allowNull: false,
        references: {
          model: "users", // Assuming reports are generated by users
          key: "id",
        },
      },
      data: {
        type: Sequelize.JSONB, // Storing metrics as a JSON object
        allowNull: false,
      },
      exportUrl: {
        type: Sequelize.STRING,
        allowNull: true,
        validate: {
          isUrl: true,
        },
      },
      createdAt: {
        type: Sequelize.DATE,
        defaultValue: Sequelize.NOW,
      },
    });
    
    module.exports = Analytics;
      