
    var sequelize = require("../db/init.sequelize.js");
    var Sequelize = require("sequelize");
    
    var Analytics = sequelize.define("analytics", {

      reportType: {
        type: Sequelize.ENUM(
          "Patient Trends",
          "Revenue",
          "Treatment Effectiveness",
          "Doctor Performance"
        ),
        allowNull: false,
      },
      startDate: {
        type: Sequelize.DATE,
        allowNull: false,
      },
      endDate: {
        type: Sequelize.DATE,
        allowNull: false,
      },
      generatedBy: {
        type: Sequelize.UUID,
        allowNull: false,
        references: {
          model: "users", // Assuming reports are generated by users
          key: "id",
        },
      },
      data: {
        type: Sequelize.JSONB, // Storing metrics as a JSON object
        allowNull: false,
      },
      exportUrl: {
        type: Sequelize.STRING,
        allowNull: true,
        validate: {
          isUrl: true,
        },
      },
      createdAt: {
        type: Sequelize.DATE,
        defaultValue: Sequelize.NOW,
      },
    });
    
    module.exports = Analytics;
      